apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "anime-life"
  name: "anime-life"
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "anime-life"
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "anime-life"
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          name: "anime-life"
          env:
            - name: "REACT_APP_ENVIRONMENT"
              value: "PROD"
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always