apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: anime-life--http
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: default-httpsredirect@kubernetescrd
spec:
  rules:
    - host: "makise-amadeus.xyz"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: anime-life
                port:
                  number: 80