apiVersion: v1
kind: Service
metadata:
  labels:
    app: "anime-life-nextjs"
  name: "anime-life-nextjs"
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: "anime-life-nextjs"
  sessionAffinity: None
  type: LoadBalancer